function showAlert(message){const alertBox2=document.createElement('div');alertBox2.classList.add('custom-alert');alertBox2.innerHTML=`
<div class="alert-box">
<span class="alert-message">${message}</span>
<button class="alert-ok">Iyo</button>
</div>`;document.body.appendChild(alertBox2);alertBox2.style.display='flex';alertBox2.querySelector('.alert-ok').addEventListener('click',()=>{alertBox2.style.display='none';document.body.removeChild(alertBox2)})}
const textarea=document.querySelector('textarea');textarea.addEventListener('focus',()=>{textarea.setAttribute('placeholder','')});textarea.addEventListener('blur',()=>{if(textarea.value===''){textarea.setAttribute('placeholder','Kirim pesen ke Tolep...')}});document.addEventListener("DOMContentLoaded",function(){const lookBtn=document.getElementById("look");const userOnline=document.getElementById("user-online");const userProf=document.getElementById("prof");lookBtn.addEventListener("click",function(e){e.stopPropagation();userOnline.classList.toggle("active");lookBtn.classList.toggle("active");userProf.classList.toggle("active")});document.addEventListener("click",function(){userOnline.classList.remove("active");lookBtn.classList.remove("active");userProf.classList.remove("active")});userOnline.addEventListener("click",function(e){e.stopPropagation()});userProf.addEventListener("click",function(e){e.stopPropagation()})});
/*! ====  FIREBASE CONFIG  ==== */
const firebaseConfig={apiKey:"AIzaSyAxhhXU90GluSwrjaoqxmP23bgfHR18ez4",authDomain:"secretserver-chat.firebaseapp.com",projectId:"secretserver-chat",storageBucket:"secretserver-chat.appspot.com",messagingSenderId:"105772354036",appId:"1:105772354036:web:b3962f9ec0260be47491a1",measurementId:"G-2FY0BDMFWD"};firebase.initializeApp(firebaseConfig);const auth=firebase.auth();const firestore=firebase.firestore();document.addEventListener("DOMContentLoaded",function(){const wowAh=document.getElementById("wow");const loadingParent=document.getElementById('loading');const loadingCircle=document.getElementById('loading-circle');function handleSignOut(){firebase.auth().signOut().then(()=>{setTimeout(()=>{window.location.href='https://tolepcoy.github.io/SS/login-form.html'},3000)})}
function checkLoginStatus(user){const userId=user.uid;console.log("User sudah login:",user.email);firestore.collection('PRIVASI').doc(userId).get().then((doc)=>{if(doc.exists){const userData=doc.data();if(userData.disabled===!0){showAlert('Akun Ente belum aktif, nunggu disetujui Tolep dulu');wowAh.style.pointerEvents='none';loadingParent.style.display='none';loadingCircle.style.display='none';loadingCircle.style.animation='none';handleSignOut()}else{if(userId!=='c5AbAGemIcfsphDrXu56I8OZyEo1'){wowAh.style.pointerEvents='auto';document.getElementById('delCBC').style.pointerEvents='none';document.getElementById('headerTolep').style.pointerEvents='none'}}}else{console.log('Dokumen PRIVASI tidak ditemukan untuk user ini.')}}).catch((error)=>{console.error('Error membaca data PRIVASI:',error)})}
firebase.auth().onAuthStateChanged((user)=>{if(user){checkLoginStatus(user)}else{console.log('User belum login!');wowAh.style.pointerEvents='none';loadingParent.style.display='flex';loadingCircle.style.display='block';loadingCircle.style.animation='spin 1s linear infinite;';window.location.href='https://tolepcoy.github.io/SS/login-form.html'}})});firebase.firestore().enablePersistence().catch(function(err){if(err.code=='failed-precondition'){console.log('Offline caching gagal karena multi-tab.')}else if(err.code=='unimplemented'){console.log('Offline caching tidak didukung di browser ini.')}});firebase.auth().onAuthStateChanged(user=>{if(user){const userRef=firestore.collection('SS').doc(user.uid);userRef.onSnapshot(doc=>{if(doc.exists){const data=doc.data();updateProfile(data,'User')}},error=>console.error("Error listening to user data:",error))}});function updateProfile(data,kategori){document.getElementById('nama').innerHTML=data.nama}
const messageForm=document.getElementById('messageForm');const messageInput=document.getElementById('messageInput');const chatBox=document.getElementById('chatBox');const chatBoxTolep=document.getElementById('chatbox-tolep');const sendButton=document.getElementById('sendButton');firebase.auth().onAuthStateChanged((user)=>{if(user){firestore.collection('SS').doc(user.uid).onSnapshot((doc)=>{if(doc.exists){const userName=doc.data().nama;messageForm.addEventListener('submit',(e)=>{e.preventDefault();const message=messageInput.value.trim();if(message==='')return;const collection=user.uid==="c5AbAGemIcfsphDrXu56I8OZyEo1"?'CHATBOX-TOLEP':'CHATBOX';firestore.collection(collection).add({nama:userName,text:message,timestamp:new Date(),userId:user.uid,});messageInput.value=''});firestore.collection('CHATBOX').orderBy('timestamp').onSnapshot((snapshot)=>{chatBox.innerHTML='';snapshot.forEach((doc)=>{const messageData=doc.data();const timestamp=messageData.timestamp?new Date(messageData.timestamp.toMillis()).toLocaleTimeString('id-ID',{hour:'2-digit',minute:'2-digit',}):'';const messageElement=document.createElement('div');messageElement.innerHTML=`
<div id="sender">
<span class="namoUwong">${messageData.nama}</span>
<div id="timetrex">${timestamp}</div>
</div>
<div id="text-chat" style="color: #090;margin-top:-15px;">${messageData.text}</div>
`;chatBox.appendChild(messageElement)});chatBox.scrollTop=chatBox.scrollHeight});firestore.collection('CHATBOX-TOLEP').orderBy('timestamp').onSnapshot((snapshot)=>{chatBoxTolep.innerHTML='';snapshot.forEach((doc)=>{const messageData=doc.data();const messageElement=document.createElement('div');messageElement.innerHTML=`
<div style="color:#9d0" id="text-chat-tolep">${messageData.text}</div>
`;chatBoxTolep.appendChild(messageElement)});chatBoxTolep.scrollTop=chatBoxTolep.scrollHeight})}})}});function bersihkanChatboxLama(){const now=new Date();const cutoff=new Date(now.getTime()-7*24*60*60*1000);const cutoffTimestamp=firebase.firestore.Timestamp.fromDate(cutoff);firestore.collection("CHATBOX").where("timestamp","<",cutoffTimestamp).get().then((snapshot)=>{snapshot.forEach((doc)=>{doc.ref.delete()})})
firestore.collection("CHATBOX-TOLEP").where("timestamp","<",cutoffTimestamp).get().then((snapshot)=>{snapshot.forEach((doc)=>{doc.ref.delete()})})}
firebase.auth().onAuthStateChanged((user)=>{if(user){firestore.collection('Administrator').doc(user.uid).get().then((doc)=>{if(doc.exists){const userData=doc.data();if(userData.isAdmin){bersihkanChatboxLama()}}})}});function updateStatusOnline(uid){firestore.collection('SS').doc(uid).update({online:!0,lastSeen:firebase.firestore.FieldValue.serverTimestamp()}).catch((error)=>{console.error("Error updating status online:",error)})}
let offlineTimer;function startOfflineTimer(uid){clearTimeout(offlineTimer);offlineTimer=setTimeout(()=>{firestore.collection('SS').doc(uid).update({online:!1,lastSeen:firebase.firestore.FieldValue.serverTimestamp()}).catch((error)=>{console.error("Error setting status offline:",error)})},120000)}
document.addEventListener('DOMContentLoaded',()=>{const inputChat=document.getElementById('messageInput');const yangOnlineElement=document.getElementById('yang-online');if(inputChat){inputChat.addEventListener('input',()=>{const user=firebase.auth().currentUser;if(user){updateStatusOnline(user.uid);startOfflineTimer(user.uid)}})}
function cekStatusSemuaOnline(){firestore.collection('SS').where('online','==',!0).onSnapshot((snapshot)=>{if(yangOnlineElement){let onlineUsers='';snapshot.forEach((doc)=>{const data=doc.data();onlineUsers+=`<div style="font-weight:bold;font-size:12px;" class="namoUwong"><li>${data.nama}</li></div>`});yangOnlineElement.innerHTML=onlineUsers||''}},(error)=>{console.error("Error fetching online users:",error)})}
firebase.auth().onAuthStateChanged((user)=>{if(user){updateStatusOnline(user.uid);startOfflineTimer(user.uid);cekStatusSemuaOnline()}})});const terminal=document.getElementById("terminal");const wow=document.getElementById("wow");const meong=document.getElementById("meong");const meong2=document.getElementById("meong2");const meong3=document.getElementById("meong3");const blinkJugo=document.getElementById("blink-jugo");const commands=[{text:"$ Load Tolep server ...",dots:3,delay:2,isGold:!0},{text:"$ Request permission",dots:4,delay:2},{text:"$ Get data from tolepserver_ ...",delay:2},{text:"$ Enable Node.js & Script ... /Done.",delay:2},{text:"$ Enabling encryption ... /Done.",delay:2},{text:"$ Getting sign-in ...",delay:2},{text:"$ Requested!",delay:2,isGreen:!0},{text:"$ Get in profile ... /Done.",delay:2},{text:"$ Encrypting chat ... /Done.",delay:2},{text:"$ Converting to base64 -REGEX ../Done.",delay:2},{text:"$ Run Script for chating ... /Done.",delay:2,isGreen:!0},{text:"$ Assistant Bot-AI Tolep Coy was checking!",delay:10,blinkTerminal:!0},{text:"$ Security locked ..../Done.",delay:1},{text:"$ Credential keys created .../Done.",delay:1},{text:"$ Loaded.",delay:1,isGreen:!0},{text:"$ Copying to server",dots:1,delay:1},{text:"$ Get in to room server ...",delay:1},{text:"$ Enable JQuery for encrypting ... /Done.",delay:1,isGold:!0},{text:"$ Enable cascading style ...",delay:1},{text:"$ Enable AJAX script .... /Done.",delay:1,isGold:!0},{text:"$ Extract encryption to Html ... /Done.",delay:1},{text:"$ Script ... /Loaded.",delay:1,isGreen:!0},{text:"$ Cascading Style Sheet ... /Loaded.",delay:1,isGreen:!0},{text:"$ Html ... /Loaded.",delay:1,isGreen:!0},{text:"$ Managing file server.",delay:1},{text:"$ Syncronize external script.",delay:1},{text:"$ Syncronized!.",delay:1,isGold:!0},{text:"$ Getting started ...",delay:1},{text:"$ Done.",delay:2,isGreen:!0},{text:"        ",delay:1},{text:"        ",delay:1},{text:"                                                  OK!   ",delay:1},{text:"$ Run!",delay:1,isGreen:!0}];let isCommandRunning=!1;function typeEffect({text,dots=0,delay=100,isRed=!1,isGreen=!1,isGold=!1,blinkTerminal=!1},callback){let i=0;const line=document.createElement("div");if(text.trim()===""){line.innerHTML="&nbsp;";terminal.appendChild(line);setTimeout(callback,delay);return}
terminal.appendChild(line);function type(){if(i<text.length){line.innerHTML+=text[i++];setTimeout(type,delay)}else if(dots>0){typeDots(dots,callback)}else{finalize(line,isRed,isGreen,isGold,blinkTerminal,callback)}}
function typeDots(dots,callback){let dotCount=0;function addDot(){if(dotCount<dots){line.innerHTML+=".";dotCount++;setTimeout(addDot,delay)}else{finalize(line,isRed,isGreen,isGold,blinkTerminal,callback)}}
addDot()}
function finalize(line,isRed,isGreen,isGold,blinkTerminal,callback){if(isRed)line.classList.add("red");if(isGreen)line.classList.add("green");if(isGold)line.classList.add("gold");if(blinkTerminal)line.classList.add("blinkTerminal");if(callback)callback();}
type()}
function runCommands(){let i=0;function nextCommand(){if(i<commands.length){typeEffect(commands[i++],nextCommand)}else{terminal.style.display="none";terminal.style.pointerEvents="none"}}
nextCommand()}
wow.addEventListener("click",()=>{if(!isCommandRunning){wow.style.display='none';wow.style.pointerEvents='none';meong.style.display="none";meong2.style.display="none";meong3.style.display="none";blinkJugo.style.animation='none';terminal.style.background='black';isCommandRunning=!0;runCommands()}});document.getElementById('keluar').addEventListener('click',()=>{const dialog=document.getElementById('custom-logout-dialog');const dialogBlur=document.querySelector(".custom-dialog");dialog.style.display='flex';dialogBlur.style.backdropFilter='blur(4px) saturate(200%)';document.getElementById('confirm-logout').addEventListener('click',()=>{auth.signOut().then(()=>{window.location.href="https://tolepcoy.github.io/SS/login-form.html"})});document.getElementById('cancel-logout').addEventListener('click',()=>{dialog.style.display='none';dialogBlur.style.display='none';dialogBlur.style.backdropFilter='none'})});const namaEl=document.getElementById('nama');const editNamaBtn=document.getElementById('edit-nama');const kenoKeluar=document.getElementById('keluar');const DORnone=document.getElementById('DOR');editNamaBtn.addEventListener('click',()=>{editNamaBtn.style.display='none';DORnone.style.display='none';kenoKeluar.style.display='none';firebase.auth().onAuthStateChanged(user=>{if(user){const userDef=firestore.collection('SS').doc(user.uid);userDef.get().then(doc=>{if(doc.exists){const data=doc.data();const lastUpdate=data.lastNamaUpdate?.toDate()||null;const now=new Date();if(lastUpdate&&(now-lastUpdate)/(1000*60*60*24)<30){const remainingDays=30-Math.floor((now-lastUpdate)/(1000*60*60*24));showAlert(`Ente cuman biso ngubah namo setiap 30 hari. Siso waktu: ${remainingDays} hari.`);editNamaBtn.style.display='block';DORnone.style.display='block';kenoKeluar.style.display='block';return}
const currentNama=namaEl.textContent.trim();namaEl.innerHTML=`
            <input type="text" id="nama-input" style="color:#0f0;background:black;" value="${currentNama}" maxlength="15" /><br>
            <button id="cancel-nama">Batal</button>
            <button id="save-nama">Simpen</button>
          `;const namaInput=document.getElementById('nama-input');const saveBtnNama=document.getElementById('save-nama');const cancelBtnNama=document.getElementById('cancel-nama');namaInput.focus();cancelBtnNama.addEventListener('click',()=>{namaEl.textContent=currentNama;editNamaBtn.style.display='block';DORnone.style.display='block';kenoKeluar.style.display='block'});saveBtnNama.addEventListener('click',async()=>{let newNama=namaInput.value.trim();function sanitizeInput(input){const docXSS=new DOMParser().parseFromString(input,'text/html');return docXSS.body.textContent||""}
if(!/^[a-zA-Z\s]{3,15}$/.test(newNama)){showAlert("Namo cuman boleh huruf samo spasi, 3 - 15 karakter.");return}
newNama=sanitizeInput(newNama);try{await userDef.update({nama:newNama,lastNamaUpdate:firebase.firestore.Timestamp.now()});localStorage.setItem('userName',newNama);namaEl.textContent=newNama;editNamaBtn.style.display='block';DORnone.style.display='block';kenoKeluar.style.display='block'}catch(error){showAlert("Gagal nyimpen namo baru, cubo lagi.")}})}else{showAlert("Terjadi kesalahan, coba lagi.");editNamaBtn.style.display='block';kenoKeluar.style.display='block'}}).catch(error=>{showAlert("Ado yang error!, cubo lagi.");editNamaBtn.style.display='block';DORnone.style.display='block';kenoKeluar.style.display='block'})}})});document.addEventListener('DOMContentLoaded',()=>{const storedName=localStorage.getItem('userName');if(storedName){namaEl.textContent=storedName}else{namaEl.textContent='Guest'}});
/*! REMOVE CHAT KHUSUS APP ANE */
const removeChatBtn=document.getElementById('headerTolep');async function removeAllChats(){try{const chatboxSnapshot=await firestore.collection('CHATBOX').get();chatboxSnapshot.forEach(async(doc)=>{await firestore.collection('CHATBOX').doc(doc.id).delete()});const chatboxTolepSnapshot=await firestore.collection('CHATBOX-TOLEP').get();chatboxTolepSnapshot.forEach(async(doc)=>{await firestore.collection('CHATBOX-TOLEP').doc(doc.id).delete()});const chatboxCBCdel=await firestore.collection('CHATBOX-CBC').get();chatboxCBCdel.forEach(async(doc)=>{await firestore.collection('CHATBOX-CBC').doc(doc.id).delete()});showAlert("Chat sudah dihapus.")}catch(error){showAlert("Ado yang error mang!")}}
removeChatBtn.addEventListener('click',()=>{removeAllChats()});
/*! REMOVE CBC KHUSUS APP ANE 2 */
const delCBC=document.getElementById('delCBC');async function removeAllChats2(){try{const chatboxCBCdel2=await firestore.collection('CHATBOX-CBC').get();chatboxCBCdel2.forEach(async(doc)=>{await firestore.collection('CHATBOX-CBC').doc(doc.id).delete()});showAlert("Chat la dihapus.")}catch(error){showAlert("Ado yang error mang!")}}
delCBC.addEventListener('click',()=>{removeAllChats2()});const textareaMerah=document.querySelector('#messageInputCBC');textareaMerah.addEventListener('focus',()=>{textareaMerah.setAttribute('placeholder','')});textareaMerah.addEventListener('blur',()=>{if(textareaMerah.value===''){textareaMerah.setAttribute('placeholder','Isi...')}});const messageFormCBC=document.getElementById('messageFormCBC');const messageInputCBC=document.getElementById('messageInputCBC');const chatBoxCBC=document.getElementById('chatbox-center');const regexPatterns=[{pattern:/@aptpkg\b/,replace:'<a href="https://github.com/tolepcoy/SS/raw/refs/heads/main/APK/C%20O%20Y_user.apk"><img id="donglot" src="icon/download.gif" style="width:50px;height:50px;border-radius:50%;border:3px solid #0f0;"/></a>'},{pattern:/@ok\b/,replace:'<img src="gambar/ok.png" style="width:98%">'},{pattern:/@apo\b/,replace:'<img src="gambar/apo.png" style="width:98%">'},{pattern:/@wk\b/,replace:'<img src="gambar/wk.webp" style="width:98%;border:1px dashed #0F0;border-radius:5px">'},{pattern:/@bk\b/,replace:'<img src="gambar/besakkelakar.png" style="width:98%">'},{pattern:/@rx\b/,replace:'<img src="admin/rx.jpg" style="width:98%;border:1px dashed #0F0;border-radius:5px">'},{pattern:/@tkl\b/,replace:'<img src="gambar/tekola.png" style="width:98%">'},];firebase.auth().onAuthStateChanged((user)=>{if(user){firestore.collection('SS').doc(user.uid).onSnapshot((doc)=>{if(doc.exists){const userName=doc.data().nama;messageFormCBC.addEventListener('submit',(e)=>{e.preventDefault();let message=messageInputCBC.value.trim();if(message==='')return;let matched=!1;regexPatterns.forEach((regex)=>{if(regex.pattern.test(message)){message=regex.replace;matched=!0}});firestore.collection('CHATBOX-CBC').add({user:userName,message:message,timestamp:firebase.firestore.FieldValue.serverTimestamp(),userId:user.uid,});messageInputCBC.value=''});firestore.collection('CHATBOX-CBC').orderBy('timestamp').onSnapshot((snapshot)=>{chatBoxCBC.innerHTML='';snapshot.forEach((doc)=>{const messageData=doc.data();const timestamp=messageData.timestamp?new Date(messageData.timestamp.toMillis()).toLocaleTimeString('id-ID',{hour:'2-digit',minute:'2-digit',}):'';const messageElement=document.createElement('div');messageElement.innerHTML=`
<div id="CBCsender">
<span class="namoUwong" id="namotengah" style="margin-bottom:2px;"><b>${messageData.user}</b></span><br>
${messageData.message}<br>
<span style="color:transparent;font-size:1px;">${timestamp}</span>
</div>
`;chatBoxCBC.appendChild(messageElement)});chatBoxCBC.scrollTop=chatBoxCBC.scrollHeight})}else{console.log('Data user tidak ditemukan di SS!')}})}else{console.log('User belum login!')}});firebase.auth().onAuthStateChanged((user)=>{if(user){const docRef=firestore.collection('DOR').doc('vibrateON');docRef.onSnapshot((doc)=>{if(doc.exists){const data=doc.data();if(data.vibrateON){console.log('Perubahan terdeteksi: vibrateON = true');if(typeof Android!=='undefined'&&Android.vibrate){Android.vibrate()}else if(navigator.vibrate){navigator.vibrate([1000,100,1000])}
docRef.set({vibrateON:!1},{merge:!0})}}});document.getElementById('DOR').addEventListener('click',function(){console.log('Tombol #DOR diklik');docRef.set({vibrateON:!0},{merge:!0}).then(()=>{console.log('Data vibrateON dikirim ke Firestore')}).catch((error)=>{console.error('Error mengirim data ke Firestore: ',error)});if(typeof Android!=='undefined'&&Android.vibrate){Android.vibrate()}else if(navigator.vibrate){navigator.vibrate([1000,100,1000])}})}});document.querySelector('#DOR').addEventListener('click',function(){this.disabled=!0;this.classList.toggle('hover');this.innerHTML='Hp Tolep berdering + geter!';setTimeout(()=>{this.classList.remove('hover');this.innerHTML='Oi lep<b>!</b>';this.disabled=!1},3000)});document.getElementById('headerTolep').addEventListener('click',function(){this.classList.toggle('hover');setTimeout(()=>{this.classList.remove('hover')},1000)});document.getElementById('delCBC').addEventListener('click',function(){this.classList.toggle('hover');setTimeout(()=>{this.classList.remove('hover')},1000)});const togCBCbtn=document.getElementById('togCBCbtn');const CBCkontener=document.getElementById('chatbox-center-container');togCBCbtn.addEventListener('click',()=>{CBCkontener.classList.toggle('action');togCBCbtn.classList.toggle('merah')})